Feature add superset example
Flexberry/Flexberry.SampleForSuperset pull request #2
Opened 2022-11-30 12:34 UTC by s-andrey

2022-11-30 13:19 UTC, bratchikov requested changes

2022-11-30 13:19 UTC, bratchikov commented on GenConfig.fdg
> +  "GenPath": "newSrc",
Давай вернёмся к src? Иначе какой-то нетрадиционный вариант получается.

2022-11-30 13:19 UTC, bratchikov commented on GenConfig.fdg
> +        "EmberApp": false,
Фронтенда нет?

2022-11-30 13:19 UTC, bratchikov commented on GenConfig.fdg
> +        "FullSql": false,
А что с БД?

2022-11-30 13:19 UTC, bratchikov commented on README.md
> +1. Создать тетовые данные (можно в web приложении нажать кнопку "Добавить тестовые данные" создает 60000 тестовых данных ps данные создается долго тк на кадрую запись пишется так же и аудит)
```suggestion
1. Создать тестовые данные (можно в web-приложении нажать кнопку "Добавить тестовые данные" создает 60000 тестовых данных, данные создается долго т.к. на каждую запись пишется так же и аудит)
```

2022-11-30 13:19 UTC, bratchikov commented on README.md
> +1. Перейти на dashboards и нажать кнопку испорта
```suggestion
1. Перейти на dashboards и нажать кнопку импорта
```

2022-11-30 13:19 UTC, bratchikov commented on src/Docker/Audit/users.xml
> +<?xml version="1.0"?>
А что это за файл? Он нужен?

2022-11-30 13:19 UTC, bratchikov commented on src/Docker/Dockerfile.PgAdmin
> +FROM dpage/pgadmin4
А зачем нам пересобирать образ, если он просто берётся из стандартного? Давай не будем делать лишних файлов.

2022-11-30 13:19 UTC, bratchikov commented on src/Docker/create-image.cmd
> +docker build --no-cache -f Dockerfile.PgAdmin -t sampleforsuperset/pgadmin4 ..
Вроде как там ничего не происходит, сборку образа можно не делать.

2022-11-30 13:19 UTC, bratchikov commented on src/Docker/vhosts.conf
> +NameVirtualHost *:80
По-моему, для .NET Core этот файл не нужен. Он использовался только для mono в Apache webServer.

2022-11-30 13:19 UTC, bratchikov commented on src/SQL/CreateDatabaseInDocker/2 create_database.sh
> +CREATE TABLE SparePart (
Похоже тут есть проблема совместимости с нашим генератором SQL. Надо разобраться можно ли выполнить скрипты, которые генерируются у нас как раньше. Может быть пример с liquibase сделать.

2022-12-01 04:25 UTC, AntonIV8 commented on README.md
> +4. Нажать `Attach to shell` и выполнить кооманду для создания таблиц аудита
А к какому контейнеру цепляться. Понять конечно не сильно трудно, но думаю надо указать, мало ли

2022-12-01 04:36 UTC, AntonIV8 commented on src/SQL/CreateDatabaseInDocker/2 create_database.sh
> +CREATE TABLE SparePart (
Тут надо наверное сделать так, как я на стенде AuditBigData переделал. Только скрипт CreateTables. Остальное все двумя строчками в Dokerfile

2022-12-01 04:41 UTC, AntonIV8 commented on src/SQL/CreateDatabaseInDocker/2 create_database.sh
> +CREATE TABLE SparePart (
В целом мне кажется надо докер часть по более понятным папкам разместить внутри папки Docker.
Databases, Application, AuditDatabase(Можно Clickhouse еще прописать). Папка SQL на уровень выше есть, и в ней чисто скрипты SQL

2022-12-01 04:45 UTC, AntonIV8 commented on src/SQL/CreateDatabaseInDocker/2 create_database.sh
> +CREATE TABLE SparePart (
В папке SQL Папка CreateDatabaseInDocker тоже не совсем понятно куда. Ну и плюс если сделать как  AuditBigDataTestStand то ее не будет, а будет только CreateAuditTablesClickhouse.sql например

2022-12-02 06:01 UTC, Anisimova2020 commented on README.md
> +3. Открыть VScode перейти в плагин для Docker-а
"Открыть VScode, перейти" - тут запятую нужно.

2022-12-02 06:15 UTC, Anisimova2020 commented on README.md
> +4. Нажать `Attach to shell` и выполнить кооманду для создания таблиц аудита
Позанудничаю :) "кооманду" -> "команду"

2022-12-02 06:18 UTC, Anisimova2020 commented on README.md
> +http://localhost:5432/ - postgres бд приложени (логин: flexberryuser пароль: jhv)
А можно другой порт? 
У меня локально по дефолту на этом порту постгрес. И когда начинаю с докером работать, то сразу же что-то в настройках нужно менять.

2022-12-02 06:23 UTC, Anisimova2020 commented on README.md
> +1. Создать тетовые данные (можно в web приложении нажать кнопку "Добавить тестовые данные" создает 60000 тестовых данных ps данные создается долго тк на кадрую запись пишется так же и аудит)
Ещё 
"можно в web-приложении нажать кнопку "Добавить тестовые данные" создает" => "можно в web-приложении нажать кнопку "Добавить тестовые данные",  создает".

И может вообще перефразировать? "нажать кнопку "Добавить тестовые данные" создает 60000 тестовых данных" => "нажать кнопку "Добавить тестовые данные", которая создаст 60000 записей тестовых данных".

"данные создается долго т.к. на каждую запись пишется так же и аудит" => "данные создаЮтся долго, т.к. на каждую запись пишется также и аудит".

2022-12-02 06:25 UTC, Anisimova2020 commented on README.md
> +2. Зайти в superset и подключить его к БД приложения
А там на картинках описано, как это сделать? Может также текстово минимально описать на случай, если картинки не подгрузились?

2022-12-02 06:40 UTC, Anisimova2020 commented on src/Docker/Audit/Dockerfile
> +#После запускаконтейнера надо в него зайти и выполнить эту команду вручную, т.к пока через докер не выходит создать таблицы
"запускаконтейнера " -> "запуска контейнера"

2022-12-02 07:05 UTC, Anisimova2020 commented on src/Docker/docker-compose.yml
> +      - 5432:5432
Может сразу изменить с дефолтного постгресного, чтобы конфликта не было?

2022-12-06 07:15 UTC, s-andrey commented on README.md
> +http://localhost:5432/ - postgres бд приложени (логин: flexberryuser пароль: jhv)
у меня тоже локальный по этому адресу, можно просто службу выключить у него и все будет хорошо работать

2022-12-06 07:20 UTC, s-andrey commented on src/Docker/Audit/users.xml
> +<?xml version="1.0"?>
в докер файле COPY users.xml /etc/clickhouse-server/users.xml

2022-12-08 08:39 UTC, Anisimova2020 commented on GenConfig.fdg
> +        "DiffSql": true,
Почему не нужен полный SQL?

2022-12-08 08:41 UTC, Anisimova2020 commented on README.md
> +http://localhost:5432/ - postgres бд приложени (логин: flexberryuser пароль: jhv)
Опечатка.

2022-12-09 12:34 UTC, merged